



GET http://localhost:5186/Problems

 
###
POST http://localhost:5186/Problems
content-Type: application/json

{
  "id": "",
  "title": "Two Sum",
  "testCases": [
    {
      "input": {
        "nums": [2, 7, 11, 15],
        "target": 9
      },
      "expectedOutput": [0, 1]
    }
  ],
  "constraints": {
    "arrayLength": "2 <= nums.length <= 10^4",
    "uniqueSolution": "Only one valid answer exists"
  }
}

###

DELETE http://localhost:5186/Problems/


### 

GET http://localhost:5186/